load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
   name = "custom_detection",
   calculators = [
     "//mediapipe/graphs/facemesh_and_iris_tracking:gpu_tracking_calculator",
   ],
)
