load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
   name = "custom_detection",
   calculators = [
     "//mediapipe/graphs/face_effect:face_effect_gpu_deps",
   ],
)
